#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

_set_liveuser_PS1() {
    PS1='[\u@\h \W]\$ '
    if [ "$(whoami)" = "liveuser" ] ; then
        local iso_version="$(grep ^VERSION= /usr/lib/endeavouros-release 2>/dev/null | cut -d '=' -f 2)"
        if [ -n "$iso_version" ] ; then
            local prefix="eos-"
            local iso_info="$prefix$iso_version"
            PS1="[\u@$iso_info \W]\$ "
        fi
    fi
}
_set_liveuser_PS1
unset -f _set_liveuser_PS1

alias ls='ls --color=auto'
alias ll='ls -lav --ignore=..'   # show long listing of all except ".."
alias l='ls -lav --ignore=.?*'   # show long listing but no hidden dotfiles except "."

# alias spotify='spt'              # spotify api
alias v='nvim'                   # neovim shortcut

# Git add and commit obsidian changes
gitobsidian() {
	git -C ~/Documents/SecondBrain add .
	git -C ~/Documents/SecondBrain commit -m "Terminal quick commit"
}

# Docker start for COMP604
# dockercomp604() {
# 	sudo systemctl start docker
#	docker start comp604
#	docker exec -it comp604 bash
#}

# Set brightness
# setbrightness() {
# 	brightnessctl -d amdgpu_bl0 s $1
# }

[[ "$(whoami)" == "root" ]] && return

[[ -z "$FUNCNEST" ]] && export FUNCNEST=100          # limits recursive functions, see 'man bash'

## Use the up and down arrow keys for finding a command in history
## (you can write some initial letters of the command first).
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

eval "$(starship init bash)"
